# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

pool:
  vmImage: 'ubuntu-16.04'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.1.300'

- script: dotnet restore

- script: dotnet build -c '$(buildConfiguration)'

- script: dotnet test  StringRandomizer.Tests/StringRandomizer.Tests.csproj --logger "trx;LogFileName=out.trx" /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura  -c  '$(buildConfiguration)'  --no-build

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'MSTest'
    testResultsFiles: 'StringRandomizer/StringRandomizer.Tests/TestResults/out.trx' 
    testRunTitle: 'Unit Test'
    buildConfiguration: '$(buildConfiguration)'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: '/StringRandomizer/StringRandomizer.Tests/coverage.cobertura.xml'

- task: CopyFiles@2
  inputs:
    targetFolder: '$(Build.ArtifactStagingDirectory)' 
    contents: '**/bin/$(buildConfiguration)/*.nupkg'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'drop'
    targetPath: '$(Build.ArtifactStagingDirectory)' 
